version: "3.8"
services: 
  postgres:
    image: postgres:14.4-alpine
    deploy:
      resources:
        limits:
#          cpus: '0.5'
          memory: 1024M
        reservations:
#          cpus: '0.25'
          memory: 512M
    container_name: postgres-14-4
    environment: 
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes: 
      - ./.docker/pg_data:/var/lib/postgresql/data
