version: "3.1"
services: 
  postgres:
    image: postgres:12.11-alpine
    container_name: postgres-12-11
    environment: 
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes: 
      - pg_data-126:/var/lib/postgresql/data
volumes: 
  pg_data-126:
    driver: local
