version: "3.1"
services: 
  postgres:
    image: postgres:12.6
    container_name: postgres-12-6
    environment: 
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes: 
      - pgdata-126:/var/lib/postgresql/data/pgdata
volumes: 
  pgdata-126:
    driver: local
