version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    container_name: jaeger-aio
    environment:
      - COLLECT_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14250:14250
      - 14268:14268
      - 16686:16686
      - 9411:9411
    