version: "3"
networks:
  gitea:
    external: false

services:
  gitea_server:
    image: gitea/gitea:1.16.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
#    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea/data:/data
      - ./gitea/etc/timezone:/etc/timezone:ro
      - ./gitea/etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
