version: "3"
services: 
  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
    hostname: localhost
    environment: 
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=Qwerty!23'
      - 'MSSQL_COLLATION=Cyrillic_General_CS_AS'
    ports:
      - 1433:1433
    volumes:
      - ./.docker/data:/var/opt/mssql/data
